### ISSUE TITLE
localhost URL get blocked

### ISSUE THREAD

**Issue by stephrom** [CompEpigen/figeno#1]
Hi,

on macOS 14.4, M1 processor the URL HTTP://localhost:5000 gets blocked : http error 403

replacing the above URL with http://127.0.0.1:5000 solves the issue, or use another port number

**Comment by e-sollier** [comment]
Hi @stephrom,
thanks for the bug report and for the solution! I've updated figeno to use 127.0.0.1 instead of localhost for macOS. If you update to v1.0.5 (`pip install figeno==1.0.5`), `figeno gui` will open a browser window at http://127.0.0.1:5000/ on macOS. I hope this is sufficient to fix the issue, but please let me know if you (or other users) still encounter http errors.
