### ISSUE TITLE
whether does figeno support URL

### ISSUE THREAD

**Issue by BenxiaHu** [CompEpigen/figeno#13]
whether does figeno support URL?

**Comment by e-sollier** [comment]
What do you mean? 
Figeno only works locally and is not available as a web service, if that's what you want to know.

**Comment by BenxiaHu** [comment]
no.
for example, you depoisted your bigwig files on amazon or google driver.
does Figeno can support the URL which links to these bigwig files? IGV does support URLs.

**Comment by e-sollier** [comment]
Ah, I see. No, figeno currently does not support URLs. I can investigate how feasible this would be to implement, but I expect this might be too much work. However, you can mount a remote filesystem (e.g. with sshfs), and use files from the mounted filesystem.

**Comment by e-sollier** [comment]
I've added experimental support for remote bigwig files. If you paste an http url in the "file" field of a bigwig track, figeno should be able to display it, although it will be slower than for a local file. However, this will only work if you have curl installed and if you reinstall pybigwig using `pip install --upgrade --force pybigwig --no-binary pybigwig` because for some reason the wheels provided for pybigwig do not seem to support remote files. I don't plan to add support for remote files for other file types, as it would take too much time.

As mentioned above, if you want to use remote files, I would suggest mounting a remote filesystem, which allows you to access those files as if they were stored on your computer. You can use sshfs if the files are on an ssh server, or https://github.com/s3fs-fuse/s3fs-fuse for amazon S3, or https://github.com/astrada/google-drive-ocamlfuse for google drive.
