### ISSUE TITLE
Make sure that the region that you specified does not extend beyond thechromosome length, and that you did not subset your .cool file.

### ISSUE THREAD

**Issue by makou1213** [CompEpigen/figeno#17]
Hello author, why am I following the normal process, but the following prompts appear:
Could not retrieve region Chr1:0-200000 in file F:\hic-data\KJ.25000.iced.matrix.cool. Make sure that the region that you specified does not extend beyond thechromosome length, and that you did not subset your .cool file.
I used the custom mode and uploaded the gtf file.

**Comment by e-sollier** [comment]
Hi,

Thanks for your interest in figeno, ans sorry for this bug.
I suspect the issue might be the capital letter in **C**hr1. Could you try replacing Chr1 with chr1 and let me know if this works? If yes, then I will update figeno to better handle capital letters in the chromosome names. Otherwise, would you be able to share the .cool file so that I can investigate?

**Comment by makou1213** [comment]
Thanks for your reply. I tried to change it to lowercase, but it still doesn't work. My chromosome is not human, can I send the .cool file to you by email?

**Comment by e-sollier** [comment]
Yes sure you can send the cool file by email (etienne[dot]sollier[at]dkfz[dot]de).

**Comment by makou1213** [comment]
Hi, the email has been sent. Please check your inbox. Thanks.

**Comment by e-sollier** [comment]
Thanks for sharing the .cool file. It turns out that the .cool file does not contain balancing weights for normalization, whereas figeno was assuming that these weights were present.
If you run `cooler balance /path/to/your/file.cool`, and then generate the figure with figeno, this should work. See https://cooler.readthedocs.io/en/latest/cli.html#cooler-balance for more information.

I will update figeno to better handle cases when these weights are missing.

**Comment by makou1213** [comment]
It is now up and running! Thank you for your guidance!
