### ISSUE TITLE
exons for select genes not showing

### ISSUE THREAD

**Issue by biovino2** [CompEpigen/figeno#18]
Hello,

I am trying to visualize gene tracks for individual genes. When populating the "genes" field for the genes track with a gene name, it correctly selects the gene and it's region, but no longer plots the exons. For example, in the figure below are three genes for the selected area:

![figure1](https://github.com/user-attachments/assets/5ca0e99d-8d13-4d51-a643-20f8c1a4fd52)

I am interested in the first gene, znf1003, so I then change the "genes" setting from auto to znf1003, and I get the following plot:

![figure2](https://github.com/user-attachments/assets/83d5738d-a06f-4945-9c3e-4431df06a885)

I also changed the "style" setting to TSS_arrow to make sure the correct gene is being selected, and it would appear that is, however the exons are no longer shown. I tried playing with several other parameters, and it seems the arrows are only shown when "genes" is set to auto. Is this a bug or am I missing a setting?

**Comment by e-sollier** [comment]
Hi,

Thanks for your interest in figeno!

I suspect there might be an issue with the genes file that you are using. Would you mind sharing the genes file that you used so that I can investigate?
I downloaded the GRCz11 genes file from the UCSC table browser (see file attached), and with this file the exons are properly displayed:
![figure_znf1003](https://github.com/user-attachments/assets/31700d9f-e82d-4f39-bff9-e1b7a2967c06)
[GRCz11_genes.txt.gz](https://github.com/user-attachments/files/16519207/GRCz11_genes.txt.gz)

**Comment by biovino2** [comment]
Thank you for your quick response!

The issue may be with using a GTF file vs. a text file, like the one you supplied. I attached the GTF file I am using. I was able to select genes and maintain their exons using your text file, but not with my GTF file.

If you can, test on fam113 instead of znf1003, because the text file does not place other genes near znf1003 like the GTF file does.
[genes.gtf.gz](https://github.com/user-attachments/files/16530952/genes.gtf.gz)

**Comment by biovino2** [comment]
It works wonderfully, thank you so much!
