### ISSUE TITLE
about bigwig peak shifting and parameter n_bins

### ISSUE THREAD

**Issue by YszSoleil** [CompEpigen/figeno#20]
Hello, there.

Everything is fine with this software except for the bigwig visualization. I have a bigwig file created by "bamCoverage" of "deeptools". Its binsize is 5 and referencing genome is mm10. However, when I use the default n_bins=500, its peak cannot match the gene exons precisely like IGV do. Then I changed the n_bins value, the peaks' position started to shift, but the outputs were still not satisfying. Hope there is a way to automatically set the right n_bins parameter.

**Comment by YszSoleil** [comment]
Find a way to solve this problem. Set n_bins = (region_end-region_start)/bin_size. However, still hope it can be calculated 
 and set automatically. : ）

**Comment by e-sollier** [comment]
Hello!

Thanks for your interest in figeno and for reporting this issue! There was indeed a problem with the bigwig track when displaying small regions (the x coordinates were imprecise). There was also a problem when the number of bins was larger than the number of bases in the region. I usually only look at rather large regions, which is why I had not noticed this earlier, but thanks a lot for reporting it! I have fixed it in version 1.4.7, which you can install with `pip install figeno==1.4.7`. With the new version, even n_bins=500 should be sufficient to get the precise positions, but you can also set an arbitrarily high number of bins to get more precise results. Please let me know if this solves your problem.
